
name: 'HAML Lint Action'
description: 'A GitHub Action that lints your HAML code with HAML Lint!'
author: 'Andrew Mason <andrewmcodes@protonmail.com>'
inputs:
  version:
    description: 'Define spcific Haml Lint gem version to use'
    required: false
  additional_gems:
    description: 'Add Additional Gems to install during setup'
    required: false
  file_paths:
    description: 'File paths for Haml Lint to analyze; typically app/views/**/*'
    required: false
  config_path:
    description: 'Path to Haml config file not in the base repo path ./'
    required: false
  exclude_paths:
    description: 'Haml lint command Exclude one or more files from being linted'
    required: false
  fail_level:
    description: 'Specify the minimum severity (warning or error) for which the lint should fail'
    required: false
    default: 'error'
  bundle:
    description: 'Useful gemfile, useful for using your oen version of the gem'
    required: false
    default: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.version }}
    - ${{ inputs.additional_gems }}
    - ${{ inputs.file_paths }}
    - ${{ inputs.config_path }}
    - ${{ inputs.exclude_paths }}
    - ${{ inputs.fail_level }}
    - ${{ inputs.bundle }}
env:
  GITHUB_TOKEN: secrets.GITHUB_TOKEN
branding:
  icon: 'code'
  color: 'orange'
