name: Linters

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  standardrb:
    name: StandardRB Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true
    - name: Run standardrb
      run: bin/standardrb
  shell_linter:
    name: Shell Lint Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Run Shell Linter
        uses: azohra/shell-linter@v0.8.0
