name: Test

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  test:
    name: Rspec Test Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Bundle
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Run Rspec
      run: bin/rspec
  dispatch:
    name: Update playground
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.DISPATCH_ACCESS_TOKEN }}
        repository: andrewmcodes/haml-lint-action-playground
        event-type: haml-lint-action-test
        client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "actor": "${{ github.actor }}"}'
